config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :quotes
  root "quotes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :quotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :authenticate_user!
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)
    @quote.user = current_user
    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "La citation a bien été créée." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "La citation a bien été modifiée." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "La citation a bien été supprimée." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:text, :author)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :pseudo, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Citation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/rails-ujs@5.2.7/lib/assets/compiled/rails-ujs.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
    <% if user_signed_in? %>
        <%= link_to current_user.email, edit_user_registration_path %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Log in", new_user_session_path %>
        <%= link_to "Register", new_user_registration_path %>
      <% end %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= simple_form_for @quote do |f| %>
  <% if quote.errors.any? %>
    <div>
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :citation %>
    <%= f.text_area :text %>
  </div>

  <div>
    <%= f.label :auteur %>
    <%= f.text_field :author %>
  </div>

  <div class="button">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/_header.html.erb
<nav class="navbar-all">
        <a class="navbar-brand" href="#">
        <%= image_tag 'Group1.png'%>
        </a>
        
        <ul class="navbar-nav">

          <li class="nav-item"><a class="nav-link " href="#">Accueil</a></li>
          </li>
          <li class="nav-item"><a class="nav-link " href="#">Écrire une citation</a></li>
          </li>
          <li class="nav-item"><a class="nav-link " href="#">Connexion</a></li>
          </li>
        </ul>
</nav>

app/views/quotes/_quote.html.erb
<div id="<%= dom_id quote %>">
  <p>
    <strong>Texte:</strong>
    <%= quote.text %>
  </p>

  <p>
    <strong>Auteur:</strong>
    <%= quote.author %>
  </p>

</div>

app/views/quotes/edit.html.erb
<nav class="navbar-all">
        <a class="navbar-brand" href="/quotes">
        <%= image_tag 'Group1.png'%>
        </a>
        
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link " href="/quotes/new">Écrire une citation</a></li>
          </li>
        </ul>
</nav>
<h1>Modifier la citation</h1>


<%= render "form", quote: @quote %>

<div>
  <%= link_to "Voir toutes les citations", @quote %> |
  <%= link_to "Retour", quotes_path %>
  <%= button_to "Modifier la citation", @quote, method: :update %>

</div>

app/views/quotes/index.html.erb
<nav class="navbar-all">
        <a class="navbar-brand" href="/quotes">
        <%= image_tag 'Group1.png'%>
        </a>
        
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link " href="/quotes/new">Écrire une citation</a></li>
          </li>
        </ul>
</nav>
<p style="color: green"><%= notice %></p>


<h1>Voir toutes les citations</h1>

<div id="quotes">
  <% @quotes.each do |quote| %>
    <%= render quote %>
    <div class="update-new">
    <p>
      <%= link_to "Modifier la citation", quote %>
    </p>
    <p>
    <%= link_to "Écrire une citation", new_quote_path %>
    </p>
    </div>
  <% end %>
</div>

app/views/quotes/new.html.erb
<nav class="navbar-all">
        <a class="navbar-brand" href="/quotes">
        <%= image_tag 'Group1.png'%>
        </a>
        
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link " href="/quotes/new">Écrire une citation</a></li>
          </li>
        </ul>
</nav>
<h1>Créer une nouvelle citation</h1>

<%= render "form", quote: @quote %>

<br>


<div>

  <%= link_to "Annuler", quotes_path%>

</div>

app/views/quotes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quote %>

<div>
  <%= link_to "Modifier la citation", edit_quote_path(@quote) %> |
  <%= link_to "Retour", quotes_path %>

  <%= button_to "Supprimer la citation", @quote, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :pseudo %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Prénom:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Nom:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Pseudo:</strong>
    <%= user.pseudo %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<nav class="navbar-all">
        <a class="navbar-brand" href="/quotes">
        <%= image_tag 'Group1.png'%>
        </a>
        
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link " href="/quotes/new">Écrire une citation</a></li>
          </li>
        </ul>
</nav>
<h1>Modifier le profil</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<nav class="navbar-all">
        <a class="navbar-brand" href="/quotes">
        <%= image_tag 'Group1.png'%>
        </a>
        
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link " href="/quotes/new">Écrire une citation</a></li>
          </li>
        </ul>
</nav>
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "Nouveau compte", new_user_path %>

app/views/users/new.html.erb
<nav class="navbar-all">
        <a class="navbar-brand" href="/quotes">
        <%= image_tag 'Group1.png'%>
        </a>
        
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link " href="/quotes/new">Écrire une citation</a></li>
          </li>
        </ul>
</nav>
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>